/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AlbumsComponent: typeof import('./src/components/AlbumsComponent.vue')['default']
    ButtonComponent: typeof import('./src/components/ButtonComponent.vue')['default']
    ButtonFieldComponent: typeof import('./src/components/ButtonFieldComponent.vue')['default']
    CardComponent: typeof import('./src/components/CardComponent.vue')['default']
    GlobalHeader: typeof import('./src/components/GlobalHeader.vue')['default']
    HamburgerMenuComponent: typeof import('./src/components/HamburgerMenuComponent.vue')['default']
    HeadingComponent: typeof import('./src/components/HeadingComponent.vue')['default']
    IconCommunity: typeof import('./src/components/icons/IconCommunity.vue')['default']
    IconDocumentation: typeof import('./src/components/icons/IconDocumentation.vue')['default']
    IconEcosystem: typeof import('./src/components/icons/IconEcosystem.vue')['default']
    IconSupport: typeof import('./src/components/icons/IconSupport.vue')['default']
    IconTooling: typeof import('./src/components/icons/IconTooling.vue')['default']
    ModalComponent: typeof import('./src/components/ModalComponent.vue')['default']
    PostsComponent: typeof import('./src/components/PostsComponent.vue')['default']
    RoundButtonComponent: typeof import('./src/components/RoundButtonComponent.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    UserTabsComponent: typeof import('./src/components/UserTabsComponent.vue')['default']
  }
}
